sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - language: php
      php: 7.2
      env: WP_TRAVISCI=phpcs

    - language: php
      php: 7.1
      env: WP_TRAVISCI=phpcs

    - language: php
      php: 7.0
      env: WP_TRAVISCI=phpcs

    - language: node_js
      node_js: 8
      env: WP_TRAVISCI=node

before_script:
  - if [[ "$WP_TRAVISCI" == "phpcs" ]]; then export PATH="$HOME/.composer/vendor/bin:$PATH"; fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
        phpenv config-rm xdebug.ini
      else
        echo "xdebug.ini does not exist"
      fi
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer install
    fi
  - if [[ "$WP_TRAVISCI" == "node" ]]; then yarn install; fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      find . -name '*.php' ! -path "./vendor/*" ! -path "./wp-content/*" -print0 | xargs -0 -n 1 -P 4 php -l
      echo Running phpcs for PHP version $TRAVIS_PHP_VERSION …
      ./vendor/bin/phpcs --runtime-set testVersion $TRAVIS_PHP_VERSION
    fi
  - if [[ "$WP_TRAVISCI" == "node" ]]; then yarn lint; fi

notifications:
  email: false
